### ISSUE TITLE
Build-time and optional dependencies annotations

### ISSUE THREAD

**Issue by ferd** [erlef/eef-build-and-packaging-wg#2]
We currently have clear distinctions for runtime deps (they go in the .app file), and the deps to be fetched (whatever the build tool wants). 

In the past the OTP team experimented with both optional and build-time deps but this was never super clearly defined.

It would be could to have clear semantics between apps that are needed at runtime, build time, and optional ones. For example, in rebar3 we willingly constrain dialyzer to run on runtime deps only to find prod issues, but that clashes a bit when that same thing is applied in test envs and so on.

Having clear semantics around how these things are expressed across languages would probably be good.

**Comment by starbelly** [comment]
I am in favor of putting these configurations in .app.src as it provides a strong seperation of concerns between rebar and OTP. Obviously, rebar3 would be responsible for parsing and doing something with such configurations initially, but it positions the feature and implementation well for inclusion in OTP. 

 If rebar were part of erlang/OTP then that would be a little different maybe, but i'm not 100% sure on that. I'd rather us not go down the path of generating .app.src files vs users knowing about them and having to understand the "architecture" of their project.

**Comment by ferd** [comment]
Short thing from a slack discussion:

1. `.app` file's `applications` works for run-time dependencies
2. `rebar.config`'s `deps` section works for compile-time dependencies
3. advocating for an `optional_applications` section in the `.app.src` file

The third point is the new one that could make sense:

- Mix could add it easily since all the app declarations are in the `mix.exs` files already
- Support can be added in OTP directly for the `optional_applications` functionality in `.app` files, for example in `applications:start/1-3` and `applications:ensure_all_started/1-2`, and in other release-handling functionality
- The change is compatible if initially only inserted in `.app.src`: tools like `rebar3` can parse that content, leave the optional value behind, and manipulate the `applications` tuple value according to what is available, the way Mix currently does it
- The change is backwards compatible, as optional applications being omitted in older versions just means they won't be there at run-time always. If something breaks, they weren't really optional.
- once OTP support is added (if ever), the clean-up work that tools like rebar3 and mix would do to the declarations would be compatible as well with the OTP desires and there would be no clash.

Tristan pointed out that ordering might be tricky for release declarations' boot order: `applications order > manual order > optional_applications order` might make the most sense.

**Comment by ferd** [comment]
Handled in the related issue (#9) and an ongoing OTP PR.
