### ISSUE TITLE
Docker image for Gleam

### ISSUE THREAD

**Issue by CrowdHailer** [erlef/eef-build-and-packaging-wg#3]
It would be good to have a supported image for working with Gleam.

There is an issue on the Gleam project to do this. https://github.com/gleam-lang/gleam/issues/515

I have been looking at trying to do this with as similar approach as the existing Docker images for erlang. However because the gleam compiler requires Rust to be built it looks like a slightly different pattern will be needed. 

I have a version one approach, using multistage builds, here https://github.com/did-app/midas-template/blob/master/Dockerfile

**Comment by ferd** [comment]
https://hub.docker.com/u/gleamlang handles this now
