### ISSUE TITLE
Maybe handle symlinking to priv in mix

### ISSUE THREAD

**Issue by starbelly** [erlef/eef-build-and-packaging-wg#4]
We sorted the problem of outputting ebin and its artifacts to the best location for mix projects via setting an environment variable in mix which tells the rebar bare compiler where to output erlang artifacts to. 

Here are the relevant issues for the above: 
- https://github.com/elixir-lang/elixir/pull/10018
- https://github.com/erlang/rebar3/pull/2060/files

 At a building and packaging meeting we discussed how priv artifacts are not still not handled. It was thought that rebar3 was responsible for this symlinking and another adjustment there would be required to resolve the issue. However, in looking into this again it is indeed mix that does the symlinking for this case. 

Here is some example output from a mix project outputting the function name in mix utils, source, target, and link : 

```
mix deps.compile 
===> Fetching pc v1.11.0
===> Analyzing applications...
===> Compiling pc
===> Compiling c_src/aead.c
===> Compiling c_src/enacl.c
===> Compiling c_src/enacl_ext.c
===> Compiling c_src/enacl_nif.c
===> Compiling c_src/generichash.c
===> Compiling c_src/hash.c
===> Compiling c_src/kdf.c
===> Compiling c_src/kx.c
===> Compiling c_src/public.c
===> Compiling c_src/pwhash.c
===> Compiling c_src/randombytes.c
===> Compiling c_src/secret.c
===> Compiling c_src/secretstream.c
===> Compiling c_src/sign.c
===> Linking /Users/starbelly/devel/elixir/links/deps/enacl/priv/enacl_nif.so
===> Analyzing applications...
===> Compiling enacl
{:do_symlink_or_copy, "/Users/starbelly/devel/elixir/links/deps/enacl/priv",
 "/Users/starbelly/devel/elixir/links/_build/dev/lib/enacl/priv",
 '../../../../deps/enacl/priv'}
```

Here is a link to the source code of the function responsible for this: https://github.com/elixir-lang/elixir/blob/367b3026630adbc7f121dfa41329f50153522c31/lib/mix/lib/mix/utils.ex#L457 

Is this an issue? If so, how should it be resolved in mix? From I understand this is all around effectively caching in CI, the only think I can think of that would not be invasive is to simply check if the MIX_ENV is test, and if so copy vs symlink. I'm not sure of any downsides to that.

**Comment by josevalim** [comment]
The first question I would ask is what is the Rebar behaviour outside of Mix. When you compile a port, does it write to the deps' `priv` dir or to the build `priv` dir? If you write to the former, then I would argue that's a behaviour you want to change in rebar itself, so everything stays in build (there are actually some complications in doing so which we can discuss later).

Another thing I discussed with @ericmj is for Rebar to track which Erlang version the current project and dependencies were compiled with. For example, at least in Rebar 0.13.1, you get this when changing Erlang versions:

```
~/OSS/hex_core[master]$ ~/.mix/rebar3 compile
===> Verifying dependencies...
===> Compiling hex_core
^C~/OSS/hex_core[master]$ ~/.mix/rebar3 shell
===> Verifying dependencies...
===> Compiling hex_core
Erlang/OTP 24 [DEVELOPMENT] [erts-11.1.1] [source-4a42e03c79] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V11.1.1  (abort with ^G)
1> hex_core:module_info().
[{module,hex_core},
 {exports,[{default_config,0},
           {module_info,0},
           {module_info,1}]},
 {attributes,[{vsn,[155284858976767814207084045567358039882]}]},
 {compile,[{version,"7.6.4"},
           {options,[debug_info,
                     {i,"/Users/jose/OSS/hex_core/_build/default/lib/hex_core/src"},
                     {i,"/Users/jose/OSS/hex_core/_build/default/lib/hex_core/include"},
                     {i,"/Users/jose/OSS/hex_core/_build/default/lib/hex_core"}]},
           {source,"/Users/jose/OSS/hex_core/src/hex_core.erl"}]},
 {md5,<<116,210,198,166,182,101,81,159,133,213,114,122,
        36,238,119,74>>}]
2>
~/OSS/hex_core[master]$ PATH="/Users/jose/.kerl/21.3.8.16/bin:$PATH"
~/OSS/hex_core[master]$ ~/.mix/rebar3 shell
===> Plugin {rebar3_hex,"6.8.0"} not available. It will not be used.
=ERROR REPORT==== 22-Oct-2020::10:07:55.450535 ===
beam/beam_load.c(1878): Error loading module rebar3_hex:
  This BEAM file was compiled for a later version of the run-time system than 21.
  To fix this, please recompile this module with an 21 compiler.
  (Use of opcode 164; this emulator supports only up to 163.)


=ERROR REPORT==== 22-Oct-2020::10:07:55.450544 ===
Loading of /Users/jose/.cache/rebar3/plugins/rebar3_hex/ebin/rebar3_hex.beam failed: badfile

===> Verifying dependencies...
===> Compiling hex_core
Erlang/OTP 21 [erts-10.3.5.12] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V10.3.5.12  (abort with ^G)
1> hex_core:module_info().
2020-10-22T10:08:15.795769+02:00 error: Loading of /Users/jose/OSS/hex_core/_build/default/lib/hex_core/ebin/hex_core.beam failed: badfile
2020-10-22T10:08:15.795761+02:00 error: beam/beam_load.c(1878): Error loading module hex_core:, This BEAM file was compiled for a later version of the run-time system than 21., To fix this, please recompile this module with an 21 compiler., (Use of opcode 169; this emulator supports only up to 163.)
** exception error: undefined function hex_core:module_info/0
2>
```

While Mix would detect this scenario and recompile. If Rebar recompiled automatically, it would actually reduce the need for `REBAR_BARE_COMPILER_OUTPUT_DIR`, but the env var is better anyway as it solves more problems, so thanks for that! :+1:

**Comment by pablocostass** [comment]
@josevalim IIRC when compiling ports, rebar3 compiles to the dep's `priv` dir and symlinks the `_build/<profile>/lib/<dep>/priv` to that.

Regarding the recompilation on Erlang version changing, @ferd has a WIP PR (https://github.com/erlang/rebar3/pull/2317) to address that.

**Comment by starbelly** [comment]
Ahh yeah, good points, it does indeed symlink to priv within the projects dir under build. Let me look into that.

```
$ pwd                                              
/Users/starbelly/devel/erlang/truecoat/_build/default/lib
$  ls -l truecoat/priv
lrwxr-xr-x  1 starbelly  staff  16 Oct 22 11:19 truecoat/priv@ -> ../../../../priv
```

**Comment by josevalim** [comment]
@starbelly right so my follow up questions are:

1. Do you want to fix this for rebar itself too?

2. If you fix it for rebar so it generates into the build priv, there is another issue: what happens if the project has a priv directory with some contents and then it also wants to generate stuff into the build's priv? We struggled a lot with trying to make both work in Elixir so we finally settled that you can have only one of them, see the docs are here: https://github.com/elixir-lang/elixir_make/blob/master/lib/mix/tasks/compile.make.ex#L82

But in a nutshell, if you want to fix it for Rebar, then fixing it for Elixir is a consequence. If you don't want to fix it for Rebar, then I wouldn't worry about fixing it for Elixir either.

**Comment by starbelly** [comment]
@josevalim I think at this point I would want to hear from @ferd or @tsloughter as they'd be the ones to accept it.

I think it's worth fixing myself, but perhaps low priority.  FWIW the way elixir is handling this makes sense to me 👍

**Comment by ferd** [comment]
The symlink to priv/ is sorta required for some support for older hooks and plugins that generate code into these directories if I recall. We broke several libs when we took it out and those are leftovers of rebar 2.x but iirc @tsloughter knows the more direct details.

**Comment by ferd** [comment]
Was this handled in another place or still blocked somehow? I recall a bunch of PRs about this having made their way through.

**Comment by starbelly** [comment]
@ferd I think there was still a problem with shared objects from nifs, I need to double check that. If I find there is still an issue I will open an agenda or PR specific to that to discuss or resolve.
