### ISSUE TITLE
RFC : UX for user registration in hex and rebar3_hex

### ISSUE THREAD

**Issue by starbelly** [erlef/eef-build-and-packaging-wg#5]
Currently in both mix hex and rebar3 hex we generally take whatever values are given and then perform an api request. This might be counter intuitive to what users expect. The main example is when values are blank and passwords mismatch. Instead of erroring out or waiting to send the values off to the api perhaps we should prompt until we get an actual submittable value. 

This is a micro issue, but UX I believe is important in our tooling, thus this RFC. In addition, I believe hex and rebar3_hex UX should be mostly equivalent, and so I think changes like this going forward should probably happen in both. 

Below is an example of what this looks like : 

```
$ rebar3 hex user register 

By registering an account on Hex.pm you accept all our policies and terms of service found at https://hex.pm/policies

Username: ([])>
===> username is required
Username: ([])>
===> username is required
Username: ([])> hunter42
Email: ([])>
===> email is required
Email: ([])> hunter42@example.com
Account Password:
===> account password is required
Account Password:
===> account password is required
Account Password:
Account Password (confirm):
===> account password confirmation is required
Account Password (confirm):
===> account password confirmation is required
Account Password (confirm):
===> account password does not match confirmation, please try again
Account Password:
Account Password (confirm):
Registering...
You are required to confirm your email to access your account, a confirmation email has been sent to hunter42@example.com
```

**Comment by starbelly** [comment]
Note: This could be taken further by making rules around username and password length, etc. available in hex_core saving both the user and hexpm an round trip to the server.

**Comment by wojtekmach** [comment]
Saving a server roundtrip sounds good to me.

My first instinct was to also move this code to hex_core given it's shared behaviour but now I'm not sure since that library is mostly about exposing APIs and this would be code for interactive terminal session (not useful for backends), so yeah, not sure.

**Comment by starbelly** [comment]
@wojtekmach possibly, we did have this issue open : https://github.com/hexpm/hex_core/issues/94 , this might be ideal for that. Possibly crypto related functions, maybe even formatters too.

**Comment by starbelly** [comment]
@wojtekmach you can comment more on your idea around opening a browser to register on hex? Would this happen as default or would the user provider a switch?

**Comment by wojtekmach** [comment]
I was thinking about a `--web` switch that would open up the web page (using `open(1)`, `xdg-open(1)`, etc)

From there I believe we have two options of going forward:

1. That's it, after we open the web page the command exits. The user would presumably register through the web ui, and then use a mix/rebar3 command to auth.
2. The command establishes communication with the server and when the registration is done successfully the control is given back to it, and it asks the user for the "local password", etc.

Option 1 is by far easier to implement so might be a better starting point. Then, option 2 will replace it. Though I wonder if makes sense to work on option 1 in the first place: I'd imagine new users that want to register probably learned about the register command from the website (hex.pm/rebar3.org) anyway, so we may as well update the docs to point to the https://hex.pm/signup link if we don't have that already. 

We've seen this terminal+opening up the web page+terminal/server communication as a way to auth e.g. heroku cli and google cloud cli and it seems pretty appealing. Even if we don't end up using it for registration flow just yet, we were thinking about using it for the auth flow. Notably, we still don't have 2FA on CLI but we do on the website, so if `mix hex.user auth --web` opens up the website as described above, we'd get 2FA "for free". These discussion were in pretty early stage, no concrete plans yet, but just fyi.

**Comment by starbelly** [comment]
I was going to add an agenda item for the next meeting around exposing TOTP auth in hex api and thus facilitating that working from the CLI :)

**Comment by ericmj** [comment]
We should consider making web auth the default since it's easier to add features to it (see the delay for 2FA), it's more secure (we can actually hide the password input reliably), and some things can only be implemented on the web, such as SSO.

It gives us less total work and everyone gets security improvements immediately without having to wait for things to implemented and clients released and updated.

**Comment by ferd** [comment]
Since an action item was created, I'll close this issue to keep agendas clean.
