### ISSUE TITLE
Better support for elixir deps in non elixir projects

### ISSUE THREAD

**Issue by starbelly** [erlef/eef-build-and-packaging-wg#7]
## Background

Currently support for elixir deps in non-elixir projects is brittle and more specifically in rebar3 projects. What can we do to rectify this situation? This is a complicated issue and I believe adjustments need to be made on both sides to facilitate strong interoperability.

## Objective(s)

 - Discuss how we can improve support for "custom" dependencies in rebar3  (see related issues)
 - Discuss the possibility of making elixir a dependency itself

## Related issue(s) : 

 - https://github.com/erlang/rebar3/issues/2419

**Comment by ferd** [comment]
Still stuck on what is essentially the same issue. @starbelly were you okay with what had been discussed and we can close this or do you want to bring it back in the next meeting?

**Comment by starbelly** [comment]
@ferd I think we can close this for now.
